name: Bug Report
description: If you have a reproducible in-game issue
labels: [ Bug ]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues.
          required: true
  - type: checkboxes
    attributes:
      label: Are you using the latest SlimColonies version?
      description: |
        Please check to see if any newer version fixes the issue you're experiencing.
      options:
        - label: |
            I am running the latest **beta/release** version of SlimColonies for my Minecraft version.
            I am also running the latest versions of other mods that are part of my problem.
          required: true
  - type: checkboxes
    attributes:
      label: Did you check existing issues?
      description: Please check if your issue has already been reported.
      options:
        - label: I checked existing issues and made sure my issue is not already reported.
          required: true
  - type: checkboxes
    attributes:
      label: What were you playing at the time? Were you able to reproduce it in both settings?
      options:
        - label: Single Player
        - label: Multi Player
  - type: input
    attributes:
      label: SlimColonies Version
      description: Exact SlimColonies version either from file name or in-game mod list.
      placeholder: 1.xx.xx-XXXX
    validations:
      required: true
  - type: textarea
    attributes:
      label: Mod Environment
      description: Please list your Forge version and any mods that might be relevant to the issue.
      placeholder: |
        Forge Version:
        Other relevant mods:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing. Please provide screenshots and videos if possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: What steps should we follow to reproduce this issue? Please provide as much detail as possible.
      placeholder: |
        1. Do this...
        2. Then this...
        3. This happens
    validations:
      required: true
  - type: input
    attributes:
      label: Logs
      description: Please provide your latest.log from when you experienced the issue. Upload to [gist](https://gist.github.com/) or [pastebin](https://pastebin.com/) and paste the link here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking any text area to highlight it and then dragging files in.
  - type: textarea
    attributes:
      label: "Footer"
      description: This is the issue footer. Please leave this text as is.
      value: |
        ---
         ## Viewers
          *  Add a 👍 reaction to the bug report if you are also affected. This helps the bug report become more visible without cluttering the comments.
          *  ⚠️ Only add a comment if you have new insights or background information not already mentioned. Off-topic or "+1" comments will be deleted to keep the discussion focused.
    validations:
      required: true
