name: Feature Request
description: Suggest a new feature or improvement for SlimColonies
labels: [Enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a similar feature has already been requested.
      options:
        - label: I have searched the existing issues.
          required: true
  - type: textarea
    attributes:
      label: Feature Description
      description: What would you like to see added or changed?
      placeholder: |
        Describe your feature idea here...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem or Motivation
      description: What problem does this solve or what motivated this request?
      placeholder: |
        I'm trying to...
        Currently it's difficult to...
        It would be nice if...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Implementation
      description: If you have ideas on how this could work, please share them (optional).
      placeholder: |
        This could work by...
        Maybe it could...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Have you tried any workarounds or alternative approaches?
      placeholder: |
        I've tried...
        Currently I work around this by...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or examples about the feature request here.
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false