blank_issues_enabled: false
contact_links:
  - name: SlimColonies Feature Request
    about: Please open a regular issue with your feature request
    url: https://github.com/haggbart/SlimColonies/issues/new
  - name: Original MineColonies Project
    about: Visit the original MineColonies project
    url: https://github.com/ldtteam/minecolonies
    
